- name: Create VMs for visitor counter application
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - openstack.cloud

  vars:
    cloud_name: xerces
    external_network: internet
    private_net_name: simple-demo-net
    private_subnet_name: simple-demo-subnet
    router_name: simple-demo-router
    cidr: 192.168.100.0/24

    security_group_name: counter-sg

    vm_snapshot: handin1-snapshot
    vm_flavor: c2m1
    vm_key_name: frtn90-key
    # vm_key_name: handin1Key

    vm_names:
      - counter-vm1
      - counter-vm2

  tasks:

    - name: Create private network
      openstack.cloud.network:
        cloud: "{{ cloud_name }}"
        name: "{{ private_net_name }}"
        state: present

    - name: Create private subnet
      openstack.cloud.subnet:
        cloud: "{{ cloud_name }}"
        name: "{{ private_subnet_name }}"
        network_name: "{{ private_net_name }}"
        cidr: "{{ cidr }}"
        ip_version: 4
        state: present

    - name: Create router and attach subnet
      openstack.cloud.router:
        cloud: "{{ cloud_name }}"
        name: "{{ router_name }}"
        network: "{{ external_network }}"
        interfaces:
          - "{{ private_subnet_name }}"
        state: present

    - name: Create security group for counter
      openstack.cloud.security_group:
        cloud: "{{ cloud_name }}"
        name: "{{ security_group_name }}"
        state: present
        security_group_rules:
          - direction: ingress
            protocol: tcp
            port_range_min: 22
            port_range_max: 22
            remote_ip_prefix: "0.0.0.0/0"
          - direction: ingress
            protocol: tcp
            port_range_min: 5000
            port_range_max: 5000
            remote_ip_prefix: "0.0.0.0/0"

    - name: Launch the two VMs from snapshot
      openstack.cloud.server:
        cloud: "{{ cloud_name }}"
        state: present
        name: "{{ vm }}"
        image: "{{ vm_snapshot }}"
        terminate_volume: true
        flavor: "{{ vm_flavor }}"
        key_name: "{{ vm_key_name }}"
        network: "{{ private_net_name }}"
        auto_ip: true
        security_groups:
          - default
          - "{{ security_group_name }}"
        wait: yes
        timeout: 300
        userdata: |
          #cloud-config
          runcmd:
            - cd /home/ubuntu/assignment1
            - . .venv/bin/activate  
      loop_control:
        loop_var: vm

