- name: Tear down visitor counter infrastructure
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - openstack.cloud

  vars:
    cloud_name: xerces
    private_net_name: simple-demo-net
    private_subnet_name: simple-demo-subnet
    router_name: simple-demo-router
    security_group_name: counter-sg

    vm_names:
      - counter-vm1
      - counter-vm2

  tasks:

    - name: Delete VMs
      openstack.cloud.server:
        cloud: "{{ cloud_name }}"
        state: absent
        name: "{{ vm }}"
        delete_fip: yes
        wait: yes
      loop: "{{ vm_names }}"
      loop_control:
        loop_var: vm

    - name: Get unattached volumes 
      openstack.cloud.volume_info: 
        cloud: "{{ cloud_name }}"
        status: available
      register: free_vols
    
    - name: Delete unattached volumes
      openstack.cloud.volume:
        cloud: "{{ cloud_name }}"
        state: absent
        name: "{{ item.id }}"
      loop: "{{ free_vols.volumes }}"
      loop_control:
        label: "{{ item.id }}"

    - name: Remove router interface
      openstack.cloud.router:
        cloud: "{{ cloud_name }}"
        name: "{{ router_name }}"
        interfaces:
          - "{{ private_subnet_name }}"
        state: absent
      ignore_errors: yes   # in case it's already detached

    - name: Delete router
      openstack.cloud.router:
        cloud: "{{ cloud_name }}"
        name: "{{ router_name }}"
        state: absent
      ignore_errors: yes

    - name: Delete subnet
      openstack.cloud.subnet:
        cloud: "{{ cloud_name }}"
        name: "{{ private_subnet_name }}"
        state: absent
      ignore_errors: yes

    - name: Delete private network
      openstack.cloud.network:
        cloud: "{{ cloud_name }}"
        name: "{{ private_net_name }}"
        state: absent
      ignore_errors: yes

    - name: Delete security group
      openstack.cloud.security_group:
        cloud: "{{ cloud_name }}"
        name: "{{ security_group_name }}"
        state: absent
      ignore_errors: yes
