---
- name: Install K3s server (control plane) on bastion
  hosts: bastion
  become: yes
  gather_facts: yes
  collections:
    - openstack.cloud

  vars:
    cloud_name: xerces
    k3s_install_url: https://get.k3s.io
    k3s_token_file: /var/lib/rancher/k3s/server/node-token
    sec_group: k3s-firewall

  tasks:
    - name: Set public IP as fact
      set_fact:
        public_ip_address: "{{ hostvars[groups['bastion'][0]]['inventory_hostname'] }}"  
      
    - name: Install K3s server
      # shell: curl -sfL {{ k3s_install_url }} | sh -
      shell: curl -sfL {{ k3s_install_url }} | INSTALL_K3S_EXEC="--tls-san={{ public_ip_address }} --flannel-backend=wireguard-native" sh -
      args:
        executable: /bin/bash

    - name: Read K3s join token
      slurp:
        src: "{{ k3s_token_file }}"
      register: k3s_token_raw

    - name: Set join token as fact
      set_fact:
        k3s_join_token: "{{ k3s_token_raw.content | b64decode | trim }}"

    - name: Get server IP
      ansible.builtin.set_fact:
        k3s_server_ip: "{{ ansible_default_ipv4.address }}"

    - name: Add server IP and token to hostvars for workers
      add_host:
        name: "{{ item }}"
        groups: joined_workers
        k3s_server_ip: "{{ k3s_server_ip }}"
        k3s_join_token: "{{ k3s_join_token }}"
      loop: "{{ groups['workers'] }}"

- name: Fetch kubeconfig from bastion to local
  hosts: bastion
  tasks:
    - name: Copy kubeconfig to /home/ubuntu
      ansible.builtin.command:
        cmd: sudo cp /etc/rancher/k3s/k3s.yaml /home/ubuntu/k3s.yaml
      become: yes
      tags: cp
 
    - name: Print bastion IP
      debug:
        msg: "Bastion IP is {{ public_ip_address }}"
      tags: ip
 
    - name: Fix kubeconfig server address
      lineinfile:
        path: /home/ubuntu/k3s.yaml
        regexp: '^    server: https://127.0.0.1:6443'
        line: "    server: https://{{ hostvars[groups['bastion'][0]]['inventory_hostname'] }}:6443"
      become: yes

    - name: Copy kubeconfig from bastion to local
      ansible.builtin.fetch:
        src: /home/ubuntu/k3s.yaml
        dest: "./"
        flat: yes
        validate_checksum: no  # Ignore checksum since k3s might be changing the file frequently
      become: true

- name: Install K3s agent on workers
  hosts: joined_workers
  become: yes
  gather_facts: yes

  tasks:
    - name: Install K3s agent
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL="https://{{ k3s_server_ip }}:6443" K3S_TOKEN="{{ k3s_join_token }}" sh 
